export type ProductCategorySeed = {
  slug: string
  name: string
  eyebrow: string
  title: string
  titleAccent: string
  description: string
}

export type ProductSeed = {
  categorySlug: string
  slug: string
  name: string
  size?: string
  image: string
  /** Proje goruntuleri galerisi - bos ise ana goruntu kullanilir */
  gallery?: string[]
  /** Kroki / kat plani goruntuleri - bagimsiz bolum */
  blueprints?: string[]
  rooms?: string
  bathrooms?: string
  capacity?: string
  usageType?: string
  description: string
  highlights: string[]
}

export const DEFAULT_CATEGORIES: ProductCategorySeed[] = [
  {
    slug: "tek-katli-celik-villalar",
    name: "Tek Katli Celik Villalar",
    eyebrow: "Celik Yapilar",
    title: "Tek Katli Celik",
    titleAccent: "Villalar",
    description:
      "Modern mimari tasarim, hizli montaj ve ekonomik fiyatlarla hayalinizdeki evi kisa surede gerceklestirin.",
  },
  {
    slug: "ikiz-celik-villalar",
    name: "Ikiz Celik Villalar",
    eyebrow: "Yan Yana Yasam",
    title: "Ikiz Celik",
    titleAccent: "Villalar",
    description: "Yan yana ozel yasam alanlari ve ekonomik cozumler.",
  },
  {
    slug: "loftlu-celik-villalar",
    name: "Loftlu Celik Villalar",
    eyebrow: "Loft Tasarim",
    title: "Loftlu Celik",
    titleAccent: "Villalar",
    description: "Yuksek tavanli, ferah ve modern loft tasarimlar.",
  },
  {
    slug: "cok-katli-celik-villalar",
    name: "Cok Katli Celik Villalar",
    eyebrow: "Geniş Yasam",
    title: "Cok Katli Celik",
    titleAccent: "Villalar",
    description: "Geniş ailelere ozel cok katli villa cozumleri.",
  },
  {
    slug: "teony-house",
    name: "Tiny House",
    eyebrow: "Tiny House",
    title: "Tiny",
    titleAccent: "House",
    description: "Kompakt, fonksiyonel ve modern mini evler.",
  },
  {
    slug: "ofis-yapilari",
    name: "Ofis Yapilari",
    eyebrow: "Is Alanlari",
    title: "Ofis",
    titleAccent: "Yapilari",
    description: "Profesyonel is alanlari ve modern ofis cozumleri.",
  },
  {
    slug: "ticari-yapilar",
    name: "Ticari Yapilar",
    eyebrow: "Isletme",
    title: "Ticari",
    titleAccent: "Yapilar",
    description: "Magaza, showroom ve isyeri cozumleri.",
  },
  {
    slug: "egitim-yapilari",
    name: "Egitim Yapilari",
    eyebrow: "Egitim",
    title: "Egitim",
    titleAccent: "Yapilari",
    description: "Okul ve egitim tesisleri cozumleri.",
  },
]

export const DEFAULT_PRODUCTS: ProductSeed[] = [
  {
    categorySlug: "tek-katli-celik-villalar",
    slug: "kugu-villa",
    name: "Kugu Villa",
    size: "100 m²",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200",
    gallery: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200",
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=1200",
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200",
    ],
    blueprints: ["/blueprint-villa-100.svg", "/blueprint-villa-2.svg"],
    rooms: "2+1",
    bathrooms: "1",
    description:
      "Modern ve sik tasarimiyla one cikan Kugu Villa, 100 m² kullanim alani ile konforu maksimuma cikarir.",
    highlights: [
      "Depreme dayanikli yapi",
      "Hizli montaj suresi",
      "Enerji verimli tasarim",
      "Ses ve isi yalitimi",
    ],
  },
  {
    categorySlug: "tek-katli-celik-villalar",
    slug: "atlas-villa",
    name: "Atlas Villa",
    size: "100 m²",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200",
    gallery: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200",
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=1200",
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200",
    ],
    blueprints: ["/blueprint-villa-100.svg", "/blueprint-villa-2.svg"],
    rooms: "2+1",
    bathrooms: "1",
    description:
      "Minimalist cizgileri ve ahsap detaylariyla dikkat ceken Atlas Villa, modern konforu sunar.",
    highlights: ["Ahşap detayli modern cephe", "Hizli kurulum", "Enerji verimli", "Dayanikli sistem"],
  },
  {
    categorySlug: "tek-katli-celik-villalar",
    slug: "kuzey-villa",
    name: "Kuzey Villa",
    size: "100 m²",
    image: "/villa-kuzey.jpg",
    rooms: "2+1",
    bathrooms: "1",
    description: "Kuzey Villa, sade planlamasi ve ferah yasam alanlariyla fonksiyonel bir cozum sunar.",
    highlights: ["Sade planlama", "Ferah yasam alanlari", "Hizli teslim", "Ekonomik cozum"],
  },
  {
    categorySlug: "tek-katli-celik-villalar",
    slug: "evren-villa",
    name: "Evren Villa",
    size: "150 m²",
    image: "/villa-evren.jpg",
    rooms: "3+1",
    bathrooms: "2",
    description: "Evren Villa, genis aileler icin tasarlanmis ferah bir tek katli villa modelidir.",
    highlights: ["Genis oda dagilimi", "Modern cephe", "Yuksek izolasyon", "Hizli montaj"],
  },
  {
    categorySlug: "tek-katli-celik-villalar",
    slug: "uzay-villa",
    name: "Uzay Villa",
    size: "170 m²",
    image: "/villa-uzay.jpg",
    rooms: "3+1",
    bathrooms: "2",
    description: "Uzay Villa, daha buyuk yasam alanlari isteyenler icin premium bir secenektir.",
    highlights: ["Premium ic mekan", "Genis yasam alani", "Dayanikli yapi", "Hizli teslim"],
  },
  {
    categorySlug: "tek-katli-celik-villalar",
    slug: "neva-villa",
    name: "Neva Villa",
    size: "128 m²",
    image: "/villa-neva.jpg",
    rooms: "2+1",
    bathrooms: "1",
    description: "Neva Villa, dengeli planlama ve modern detaylarla konforlu bir yasam sunar.",
    highlights: ["Dengeli planlama", "Modern detaylar", "Enerji verimli", "Hizli kurulum"],
  },
  {
    categorySlug: "ikiz-celik-villalar",
    slug: "ikiz-120",
    name: "Ikiz 120 Villa",
    size: "120 m² (Her Biri)",
    image: "/twin-villa-1.jpg",
    rooms: "3",
    bathrooms: "2",
    description: "Yan yana planlanan iki bagimsiz yasam alaniyla ekonomik cozum sunar.",
    highlights: ["Ayni parselde iki konut", "Esit metraj", "Hizli teslim", "Enerji verimli"],
  },
  {
    categorySlug: "ikiz-celik-villalar",
    slug: "ikiz-140",
    name: "Ikiz 140 Villa",
    size: "140 m² (Her Biri)",
    image: "/twin-villa-1.jpg",
    rooms: "3",
    bathrooms: "2",
    description: "Genisleyen yasam alanlari ve ferah salonuyla aileler icin tasarlandi.",
    highlights: ["Ferah salon", "Simetrik plan", "Depreme dayanikli", "Yuksek yalitim"],
  },
  {
    categorySlug: "ikiz-celik-villalar",
    slug: "ikiz-160",
    name: "Ikiz 160 Villa",
    size: "160 m² (Her Biri)",
    image: "/twin-villa-1.jpg",
    rooms: "4",
    bathrooms: "2",
    description: "Daha fazla oda ihtiyaci olan aileler icin tasarlandi.",
    highlights: ["Genis oda sayisi", "Esnek planlama", "Hizli montaj", "Uzun omurlu"],
  },
  {
    categorySlug: "loftlu-celik-villalar",
    slug: "loft-140",
    name: "Loft 140 Villa",
    size: "140 m²",
    image: "/loft-villa-1.jpg",
    rooms: "3",
    bathrooms: "2",
    description: "Yuksek tavanli ferah alanlariyla dikkat ceker.",
    highlights: ["Yuksek tavan", "Aydinlik ic mekan", "Modern tasarim", "Hizli kurulum"],
  },
  {
    categorySlug: "loftlu-celik-villalar",
    slug: "loft-170",
    name: "Loft 170 Villa",
    size: "170 m²",
    image: "/loft-villa-1.jpg",
    rooms: "3",
    bathrooms: "2",
    description: "Genisleyen yasam alanlari ve esnek planlama imkanlari sunar.",
    highlights: ["Genis yasam alanlari", "Esnek plan", "Enerji verimli", "Dayanikli sistem"],
  },
  {
    categorySlug: "loftlu-celik-villalar",
    slug: "loft-200",
    name: "Loft 200 Villa",
    size: "200 m²",
    image: "/loft-villa-1.jpg",
    rooms: "4",
    bathrooms: "3",
    description: "Genis aileler icin tasarlanmis, bol isik alan bir konfor sunar.",
    highlights: ["4+ oda", "Premium tasarim", "Guclu yapi", "Hizli teslim"],
  },
  {
    categorySlug: "cok-katli-celik-villalar",
    slug: "alfa-villa",
    name: "Alfa Villa",
    size: "180 m²",
    image: "/multi-villa-1.jpg",
    rooms: "3+1",
    bathrooms: "2",
    description: "Cok katli celik yapida konfor ve estetik dengeleyen bir tasarimdir.",
    highlights: ["Genis salon", "3+1 plan", "Yuksek yalitim", "Hizli montaj"],
  },
  {
    categorySlug: "cok-katli-celik-villalar",
    slug: "beta-villa",
    name: "Beta Villa",
    size: "200 m²",
    image: "/multi-villa-2.jpg",
    rooms: "4+1",
    bathrooms: "2",
    description: "Genis aileler icin tasarlanmis modern bir cok katli villa modelidir.",
    highlights: ["4+1 plan", "Modern cephe", "Dayanikli karkas", "Enerji verimli"],
  },
  {
    categorySlug: "cok-katli-celik-villalar",
    slug: "gamma-villa",
    name: "Gamma Villa",
    size: "220 m²",
    image: "/project-3.jpg",
    rooms: "4+2",
    bathrooms: "3",
    description: "Genis aileler ve misafir alanlari icin tasarlanmis cok katli yasam alanidir.",
    highlights: ["4+2 plan", "Esnek ic mekan", "Guclu yapi", "Hizli teslim"],
  },
  {
    categorySlug: "cok-katli-celik-villalar",
    slug: "delta-villa",
    name: "Delta Villa",
    size: "250 m²",
    image: "/project-5.jpg",
    rooms: "5+2",
    bathrooms: "3",
    description: "Maksimum konfor ve genis alan isteyenler icin tasarlandi.",
    highlights: ["5+2 plan", "Premium ic mekan", "Uzun omurlu", "Modern mimari"],
  },
  {
    categorySlug: "teony-house",
    slug: "teony-35",
    name: "Tiny 35",
    size: "35 m²",
    image: "/tiny-house-1.jpg",
    rooms: "1",
    bathrooms: "1",
    description: "Kompakt yasam alanlari icin tasarlanmis fonksiyonel bir tiny house cozumudur.",
    highlights: ["Kompakt plan", "Hizli kurulum", "Enerji verimli", "Yalitım"],
  },
  {
    categorySlug: "teony-house",
    slug: "teony-45",
    name: "Tiny 45",
    size: "45 m²",
    image: "/tiny-house-1.jpg",
    rooms: "2",
    bathrooms: "1",
    description: "Daha genis yasam alanlari ve iki odali planlamasiyla ideal bir secenektir.",
    highlights: ["2 odali plan", "Modern tasarim", "Hizli teslim", "Ekonomik"],
  },
  {
    categorySlug: "teony-house",
    slug: "teony-55",
    name: "Tiny 55",
    size: "55 m²",
    image: "/tiny-house-1.jpg",
    rooms: "2",
    bathrooms: "1",
    description: "Daha genis alan isteyenler icin tasarlandi.",
    highlights: ["Geniş alan", "Dayanikli karkas", "Kaliteli yalitim", "Esnek duzen"],
  },
  {
    categorySlug: "ofis-yapilari",
    slug: "ofis-300",
    name: "Ofis Yapisi 300",
    size: "300 m²",
    image: "/office-1.jpg",
    capacity: "20-30 Kisi",
    description: "Orta olcekli ekipler icin fonksiyonel bir is ortami sunar.",
    highlights: ["Esnek planlama", "Hizli kurulum", "Modern cephe", "Enerji verimli"],
  },
  {
    categorySlug: "ofis-yapilari",
    slug: "ofis-500",
    name: "Ofis Yapisi 500",
    size: "500 m²",
    image: "/office-1.jpg",
    capacity: "40-50 Kisi",
    description: "Genis ekipler icin optimize edilmis modul bir yapi sunar.",
    highlights: ["Moduler alan", "Toplanti alanlari", "Hizli teslim", "Dayanikli"],
  },
  {
    categorySlug: "ofis-yapilari",
    slug: "ofis-800",
    name: "Ofis Yapisi 800",
    size: "800 m²",
    image: "/office-1.jpg",
    capacity: "60-80 Kisi",
    description: "Kurumsal firmalarin ihtiyaclarini karsilayan genis hacimli bir ofis cozumudur.",
    highlights: ["Kurumsal hacim", "Akilli alan dagilimi", "Isı yalitimi", "Hizli montaj"],
  },
  {
    categorySlug: "ticari-yapilar",
    slug: "ticari-250",
    name: "Ticari Yapi 250",
    size: "250 m²",
    image: "/commercial-1.jpg",
    usageType: "Magaza/Showroom",
    description: "Vitrin alanlari ve musteri deneyimi icin optimize edilmis kompakt bir yapi.",
    highlights: ["Showroom odakli", "Hizli kurulum", "Dayanikli sistem", "Vitrin opsiyonu"],
  },
  {
    categorySlug: "ticari-yapilar",
    slug: "ticari-400",
    name: "Ticari Yapi 400",
    size: "400 m²",
    image: "/commercial-1.jpg",
    usageType: "Restoran/Kafe",
    description: "Yeme-icme mekanlari icin uygun hacim ve servis alanlariyla planlanmistir.",
    highlights: ["Servis akisi", "Mutfak alanlari", "Kolay bakim", "Hizli teslim"],
  },
  {
    categorySlug: "ticari-yapilar",
    slug: "ticari-600",
    name: "Ticari Yapi 600",
    size: "600 m²",
    image: "/commercial-1.jpg",
    usageType: "Alisveris Merkezi",
    description: "Birden fazla isletme icin planlanmis genis hacimli bir ticari yapidir.",
    highlights: ["Moduler bolumler", "Genis vitrin", "Uzun omurlu", "Enerji verimli"],
  },
  {
    categorySlug: "egitim-yapilari",
    slug: "egitim-400",
    name: "Egitim Yapisi 400",
    size: "400 m²",
    image: "/education-1.jpg",
    usageType: "Anaokulu/Kres",
    description: "Cocuklarin guvenligi ve konforu icin tasarlanmis bir okul yapisidir.",
    highlights: ["Guvenli yapi", "Ferah siniflar", "Dayanikli malzeme", "Hizli kurulum"],
  },
  {
    categorySlug: "egitim-yapilari",
    slug: "egitim-800",
    name: "Egitim Yapisi 800",
    size: "800 m²",
    image: "/education-1.jpg",
    usageType: "Ilkokul/Ortaokul",
    description: "Daha genis ogrenci kapasiteleri icin planlanmis modul bir yapi sunar.",
    highlights: ["Moduler planlama", "Etkinlik alanlari", "Isı yalitimi", "Hizli teslim"],
  },
  {
    categorySlug: "egitim-yapilari",
    slug: "egitim-1200",
    name: "Egitim Yapisi 1200",
    size: "1200 m²",
    image: "/education-1.jpg",
    usageType: "Lise/Kurs Merkezi",
    description: "Genis kapsamli egitim tesisleri icin tasarlanmis bir yapi.",
    highlights: ["Genis kapasite", "Esnek bolumlendirme", "Uzun omurlu", "Hizli montaj"],
  },
]
